- name: Listen to Events
  hosts: localhost
  sources:
  - name: Listen to the Host and Port
    ansible.eda.webhook:
      host: 0.0.0.0
      port: 5001
  rules:
  #
  # Just print the payload
  #
  - name: print output
    condition: event.payload is defined
    action:
      debug:
        msg:
          - EVENT WAS NOT PROCESSED
          - "EVENT IS  {{ event }}"
